"""
Git operations for creating fix PRs
"""

import os
import logging
from azure.devops.connection import Connection
from msrest.authentication import BasicAuthentication
from azure.devops.v7_0.git.models import GitPullRequest, GitPullRequestCommentThread


class GitOperations:
    """Handle Git operations for auto-fix PRs"""
    
    def __init__(self):
        self.org_url = os.getenv("ADO_ORG_URL")
        self.pat = os.getenv("ADO_PAT")
        
        if not self.org_url or not self.pat:
            raise ValueError("ADO_ORG_URL and ADO_PAT must be set")
        
        credentials = BasicAuthentication('', self.pat)
        self.connection = Connection(base_url=self.org_url, creds=credentials)
        self.git_client = self.connection.clients.get_git_client()
    
    async def create_fix_pr(
        self,
        project: str,
        repo_name: str,
        source_branch: str,
        fix_description: str,
        file_changes: dict,
        rca: dict
    ) -> dict:
        """
        Create a PR with the suggested fix
        
        Args:
            project: Azure DevOps project name
            repo_name: Repository name
            source_branch: Branch that failed (e.g., 'refs/heads/main')
            fix_description: Description of the fix
            file_changes: Dict of {file_path: new_content}
            rca: Root cause analysis details
        
        Returns:
            dict with PR details
        """
        try:
            # Extract branch name from ref
            if source_branch.startswith('refs/heads/'):
                base_branch = source_branch.replace('refs/heads/', '')
            else:
                base_branch = source_branch
            
            # Create fix branch name
            fix_branch_name = f"auto-fix/{rca['category'].lower()}-{os.urandom(4).hex()}"
            
            logging.info(f"Creating PR from {fix_branch_name} to {base_branch}")
            
            # Get repository
            repos = self.git_client.get_repositories(project)
            repo = next((r for r in repos if r.name == repo_name), None)
            
            if not repo:
                raise ValueError(f"Repository {repo_name} not found")
            
            # Create PR title and description
            pr_title = f"🤖 Auto-fix: {rca['category'].replace('_', ' ').title()}"
            pr_description = f"""
## Automated Fix by Agentic DevOps Healing

**Issue Detected:** {rca['category']}  
**Confidence:** {rca['confidence'] * 100:.0f}%

### Root Cause
{rca['explanation']}

### Changes Made
{fix_description}

---
*This PR was automatically generated by AI analysis of pipeline failure.*
*Please review before merging.*
"""
            
            # For now, create PR without actual file changes
            # (Full implementation would use Git API to create commits)
            
            logging.warning("PR creation placeholder - not creating actual PR yet")
            logging.info(f"Would create PR: {pr_title}")
            logging.info(f"Branch: {fix_branch_name} -> {base_branch}")
            logging.info(f"Files to change: {list(file_changes.keys())}")
            
            return {
                "pr_id": None,
                "pr_url": f"{self.org_url}/{project}/_git/{repo_name}/pullrequest/new",
                "title": pr_title,
                "status": "placeholder"
            }
            
        except Exception as e:
            logging.error(f"Error creating PR: {str(e)}")
            raise